Kubernetes intro
otus-kuber-2020-04/maxbublik_platform pull request #2
Opened 2020-05-08 08:40 UTC by maxbublik

# Выполнено ДЗ № 1

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - образ с приложением: Dockerfile, внутри nginx unit
 - образ опубликован на Docker Hub [codecomrade/otus-kuber](https://hub.docker.com/r/codecomrade/otus-kuber) под тегом `:kubernetes-intro`
 - pod spec, внутри контейнер с приложением + init контейнер скачивающий index.html + зашареный маунт

## Как запустить проект:

Собрать образ и отправить его в Docker Hub

```
docker build -t codecomrade/otus-kuber:kubernetes-intro -f kubernetes-intro/web/Dockerfile kubernetes-intro/web
docker push codecomrade/otus-kuber:kubernetes-intro
```

Создать pod, пробросить порт

```
kubectl apply -f kubernetes-intro/web-pod.yaml
kubectl port-forward --address 0.0.0.0 pod/web 8000:8000
```

## Как проверить работоспособность:

открыть браузер `http://ip_адрес_машины_с_кубером:8000`

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-05-08 17:31 UTC, Jasstkn requested changes
Добрый вечер! 
В целом с целью задания вы справились верно - под с нужным функционалом работаю, автотесты пройдены. Однако, в домашнем задании необходимо было поработать с изменением пользователя, от которого запускаются процессы в контейнере - оставила соответствующие комментарии к докерфайлу. А также указать в домашнем задании разницу в механизме запуска kube-api-server & core-dns (слайд 2.11). Если хотите - буду рада вашему фидбеку от использования MicroK8S - расскажите, в каком облаке производили инсталляцию, с какими встретились сложностями, может быть плюсами и минусами, если использовали другие инструменты для локальной разработки и тестирования кубернетеса =)

Также хочу вас мотивировать попробовать выполнить задание со звездочкой: рекомендую воспользоваться следующим алгоритмом:
1. деплой приложения как есть
2. kubectl describe <pod_name> - внимательно ознакомьтесь с выводом данной команды
3. kubectl logs -f <pod_name> - даст вам вполне конкретную подсказку к действиям!

Если будут вопросы - пролистайте чатик, ваши коллеги уже обсуждали возможные пути решения этой задачи.  =)

2020-05-08 17:31 UTC, Jasstkn commented on kubernetes-intro/web/Dockerfile
> +    ' > /var/lib/unit/conf.json \
в данном случае лучше использовать файл и добавлять его в Dockerfile при помощи команды:
COPY <filename> <path>

2020-05-08 17:31 UTC, Jasstkn commented on kubernetes-intro/web/Dockerfile
> +]
Не вижу у вас переключения пользователя на пользователя с UID 1001:
```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8068  3764 ?        Ss   17:21   0:00 unit: main v1.17.0 [unitd --no-daemon --log /dev/stdout --pid /var/run/unit/unit.pid -
nobody       9  0.0  0.0  18312   500 ?        S    17:21   0:00 unit: controller
nobody      10  0.0  0.0 166052  3728 ?        Sl   17:21   0:00 unit: router
root        18  0.0  0.0   2388   764 pts/0    Ss   17:21   0:00 sh
root       354  0.0  0.0   7640  2716 pts/0    R+   17:22   0:00 ps aux
# whoami
root
# cat /etc/passwd | grep nobody
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
```

2020-08-03 14:56 UTC, maxbublik commented on kubernetes-intro/web/Dockerfile
> +]
пользователя поправил в [этом коммите](https://github.com/otus-kuber-2020-04/maxbublik_platform/pull/2/commits/1b70cb9a2430e99cf27da3df7ede2c8157e5f95e)

2020-08-03 14:58 UTC, maxbublik commented
@Jasstkn Мария, задание со звездочкой сделаю потом.

2020-08-03 19:41 UTC, Jasstkn approved these changes

2020-08-03 19:41 UTC, merged